library(scran)
library(Matrix)
library(Seurat)
library(RColorBrewer)
library(slingshot)
library(monocle)
library(gam)
library(ggplot2)

library(MAST)
library(clusterExperiment)
library(SingleCellExperiment)
library(monocle3)
library(destiny)
library(circlize)
library(pheatmap)
library(monocle3)
library(SeuratWrappers)
library(magrittr) # needs to be run every time you start R and want to use %>%

library(plyr)
library(dplyr)  
library(SeuratDisk)
library(SeuratData)
library(Biostrings)
library(rhdf5)
